/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chatapp;
import java.io.*;
import java.net.*;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Imad Hassi
 */
public class SignUp extends javax.swing.JFrame {

    private String selectedAvatar = "😊"; // Default avatar

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        signupUserField = new javax.swing.JTextField();
        signupConfirmButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelAvatar = new javax.swing.JLabel();
        avatarPanel = new javax.swing.JPanel();
        avatarButton1 = new javax.swing.JButton();
        avatarButton2 = new javax.swing.JButton();
        avatarButton3 = new javax.swing.JButton();
        avatarButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("Username");
        jLabelAvatar.setText("Choose Avatar:");

        avatarButton1.setText("😊");
        avatarButton1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 48)); // Try Segoe UI Symbol
        avatarButton1.setPreferredSize(new java.awt.Dimension(60, 60));
        avatarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatarButton1ActionPerformed(evt);
            }
        });

        avatarButton2.setText("😢");
        avatarButton2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 48)); // Try Segoe UI Symbol
        avatarButton2.setPreferredSize(new java.awt.Dimension(60, 60));
        avatarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatarButton2ActionPerformed(evt);
            }
        });

        avatarButton3.setText("🤖");
        avatarButton3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 48)); // Try Segoe UI Symbol
        avatarButton3.setPreferredSize(new java.awt.Dimension(60, 60));
        avatarButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatarButton3ActionPerformed(evt);
            }
        });

        avatarButton4.setText("👻");
        avatarButton4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 48)); // Try Segoe UI Symbol
        avatarButton4.setPreferredSize(new java.awt.Dimension(60, 60));
        avatarButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatarButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout avatarPanelLayout = new javax.swing.GroupLayout(avatarPanel);
        avatarPanel.setLayout(avatarPanelLayout);
        avatarPanelLayout.setHorizontalGroup(
            avatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avatarPanelLayout.createSequentialGroup()
                .addComponent(avatarButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avatarButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avatarButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avatarButton4))
        );
        avatarPanelLayout.setVerticalGroup(
            avatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(avatarButton1)
                .addComponent(avatarButton2)
                .addComponent(avatarButton3)
                .addComponent(avatarButton4))
        );

        signupConfirmButton.setBackground(new java.awt.Color(153, 255, 255));
        signupConfirmButton.setText("SignUp");
        signupConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupConfirmButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SIGN-UP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(signupUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAvatar)
                    .addComponent(avatarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupConfirmButton))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelAvatar)
                .addGap(5, 5, 5)
                .addComponent(avatarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signupConfirmButton)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avatarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatarButton1ActionPerformed
        selectedAvatar = "😊";
        JOptionPane.showMessageDialog(this, "Avatar selected: " + selectedAvatar);
    }//GEN-LAST:event_avatarButton1ActionPerformed

    private void avatarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatarButton2ActionPerformed
        selectedAvatar = "😢";
        JOptionPane.showMessageDialog(this, "Avatar selected: " + selectedAvatar);
    }//GEN-LAST:event_avatarButton2ActionPerformed

    private void avatarButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatarButton3ActionPerformed
        selectedAvatar = "🤖";
        JOptionPane.showMessageDialog(this, "Avatar selected: " + selectedAvatar);
    }//GEN-LAST:event_avatarButton3ActionPerformed

    private void avatarButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatarButton4ActionPerformed
        selectedAvatar = "👻";
        JOptionPane.showMessageDialog(this, "Avatar selected: " + selectedAvatar);
    }//GEN-LAST:event_avatarButton4ActionPerformed

    private void signupConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupConfirmButtonActionPerformed
        // TODO add your handling code here:
        String username = signupUserField.getText().trim();
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a username");
            return;
        }
        
        // Save username and avatar to file for server validation
        File usersFile = new File("users.txt");
        try (PrintWriter writer = new PrintWriter(new FileWriter(usersFile, true))) {
            writer.println(username + ":" + selectedAvatar);
            writer.flush(); // Ensure data is written immediately
            JOptionPane.showMessageDialog(this, "Signup successful for: " + username + " " + selectedAvatar);
            System.out.println("User saved: " + username + selectedAvatar + " to file: " + usersFile.getAbsolutePath());
            new ChatApp().setVisible(true);
            this.dispose();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving username: " + e.getMessage());
            System.err.println("Failed to save user: " + e.getMessage());
        }
    }//GEN-LAST:event_signupConfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avatarButton1;
    private javax.swing.JButton avatarButton2;
    private javax.swing.JButton avatarButton3;
    private javax.swing.JButton avatarButton4;
    private javax.swing.JPanel avatarPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAvatar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton signupConfirmButton;
    private javax.swing.JTextField signupUserField;
    // End of variables declaration//GEN-END:variables
}
